backend:
  ecc_key: 878787

mongo:
  host: localhost
  port: 27017
  db: badge

redis:
  host: localhost
  port: 6379
  game_nonce_expire: 3600 # 60 minute
  user_station_pair_expire: 360 # 6 minutes

rectf:
  api_key: "reRErERe-C7F-4F7B-8A3B-1E2D3C4B5A6B"

hitcon:
  secret: secret