version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: backend-mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: backend-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  mongo-data:
