station_key_ir: 10.ir.keyA
station_key_xb: 10.xb.keyB
usb_port: /dev/ttyACM0
usb_baudrate: 115200
usb_timeout: 1
wait_timeout: 3
packet_stay_timeout: 0.3
failure_try: 3
failure_wait: 0.1
packet_que_max: 1000
duplex: True